In [1]:
from espnet2.train.dataset import ESPnetDataset

/home/fujie/work/2023/yamashita/fujie_tmp/espnet/tools/venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [4]:
ds = ESPnetDataset([(
    "./dump/22k/xvector/dev/xvector.scp",
    "xvector",
    "kaldi_ark")])

In [20]:
import numpy as np
np.set_printoptions(precision=2)
np.set_printoptions(suppress=True, floatmode='fixed')


[ 1.80 -0.46 -3.26 -3.99 -0.99 -2.38 -0.50  0.01  1.83 -0.27]


In [23]:
for i in range(10):
    print(ds[i][0])
    print(ds[i][1]['xvector'][:10])

jvs001_ONOMATOPEE300_222
[ 1.80 -0.46 -3.26 -3.99 -0.99 -2.38 -0.50  0.01  1.83 -0.27]
jvs001_TRAVEL1000_0009
[ 3.34 -1.58 -1.70 -2.43 -0.64 -1.70 -1.57  0.51  1.96 -2.17]
jvs001_TRAVEL1000_0164
[ 2.22 -2.09 -2.70 -2.29  1.14 -2.18 -0.97  0.24  2.94 -0.89]
jvs001_TRAVEL1000_0340
[ 3.53 -0.50 -1.68 -4.00 -1.01 -0.36 -0.58 -0.04  1.38  0.77]
jvs001_TRAVEL1000_0397
[ 3.12 -0.35 -0.81 -0.92  0.14 -1.89 -1.33  2.67  2.88  1.11]
jvs002_ONOMATOPEE300_036
[-2.74  1.00  1.44 -1.30 -4.20  2.13 -0.46  0.88  0.95  3.01]
jvs002_TRAVEL1000_0292
[-0.63  0.63  1.83  0.66 -5.11  1.23 -0.64  2.10  1.49  2.92]
jvs002_TRAVEL1000_0312
[-1.32 -0.27  1.95 -0.40 -3.77  0.08 -0.46  2.00  2.11  3.00]
jvs002_TRAVEL1000_0481
[-2.69  2.54  1.39 -0.23 -2.62  2.48  0.64  1.67  3.70  2.09]
jvs002_TRAVEL1000_0492
[-0.48  0.61  2.05 -0.09 -2.64  0.20 -0.11  2.26  5.03  4.29]
